@files = (
    ['//procedure[procedureName="CreateLMConnection"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'LabManagerCreateConfigForm.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="LabManagerCreateConfigForm"]/value',   'LabManagerCreateConfigForm.xml'],
    ['//property[propertyName="ui_forms"]/propertySheet/property[propertyName="LabManagerEditConfigForm"]/value',     'LabManagerEditConfigForm.xml'],

    ['//property[propertyName="preamble"]/value',   'preamble.pl'],
    ['//property[propertyName="LabManager"]/value', 'LabManager.pm'],

    ['//procedure[procedureName="CreateLMConnection"]/step[stepName="CreateLMConnection"]/command',        'conf/createcfg.pl'],
    ['//procedure[procedureName="CreateLMConnection"]/step[stepName="CreateAndAttachCredential"]/command', 'conf/createAndAttachCredential.pl'],
    ['//procedure[procedureName="CreateLMConnection"]/step[stepName="AttemptConnection"]/command',         'conf/attemptConnection.pl'],
    ['//procedure[procedureName="DeleteLMConnection"]/step[stepName="DeleteLMConnection"]/command',        'conf/deletecfg.pl'],

    ['//procedure[procedureName="Provision"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                            'forms/Provision-Form.xml'],
    ['//procedure[procedureName="Provision"]/step[stepName="Provision"]/command',                                                       'labmanager/provision.pl'],
    ['//procedure[procedureName="Provision"]/step[stepName="SetTimelimit"]/command',                                                    'setTimelimit.pl'],
    ['//procedure[procedureName="Provision4.0"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                         'forms/Provision4-Form.xml'],
    ['//procedure[procedureName="Provision4.0"]/step[stepName="Provision"]/command',                                                    'labmanager/provision4.pl'],
    ['//procedure[procedureName="Provision4.0"]/step[stepName="SetTimelimit"]/command',                                                 'setTimelimit.pl'],
    ['//procedure[procedureName="Cleanup"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                              'forms/Cleanup-Form.xml'],
    ['//step[stepName="Cleanup"]/command',                                                                                              'labmanager/cleanup.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="Command"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                              'forms/Command-Form.xml'],
    ['//step[stepName="Command"]/command',                                                                                              'labmanager/command.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="Snapshot"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                             'forms/Snapshot-Form.xml'],
    ['//step[stepName="Snapshot"]/command',                                                                                             'labmanager/snapshot.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="Revert"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                               'forms/Revert-Form.xml'],
    ['//step[stepName="Revert"]/command',                                                                                               'labmanager/revert.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="Capture"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                              'forms/Capture-Form.xml'],
    ['//step[stepName="Capture"]/command',                                                                                              'labmanager/capture.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="ConfigurationChangeOwner"]/propertySheet/property[propertyName="ec_parameterForm"]/value',             'forms/ConfigurationChangeOwner-Form.xml'],
    ['//step[stepName="ConfigurationChangeOwner"]/command',                                                                             'labmanager/configurationChangeOwner.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="CreateConfigurationFromVMTemplate"]/propertySheet/property[propertyName="ec_parameterForm"]/value',    'forms/CreateConfigurationFromVMTemplate-Form.xml'],
    ['//step[stepName="CreateConfigurationFromVMTemplate"]/command',                                                                    'labmanager/createConfigurationFromVMTemplate.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="CreateConfigurationFromVMTemplate4.0"]/propertySheet/property[propertyName="ec_parameterForm"]/value', 'forms/CreateConfigurationFromVMTemplate4-Form.xml'],
    ['//step[stepName="CreateConfigurationFromVMTemplate"]/command',                                                                    'labmanager/createConfigurationFromVMTemplate4.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="Deploy"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                               'forms/Deploy-Form.xml'],
    ['//step[stepName="Deploy"]/command',                                                                                               'labmanager/deploy.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="Clone"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                                'forms/Clone-Form.xml'],
    ['//step[stepName="Clone"]/command',                                                                                                'labmanager/clone.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="CreateResourcesFromConfiguration"]/propertySheet/property[propertyName="ec_parameterForm"]/value',     'forms/CreateResourcesFromConfiguration-Form.xml'],
    ['//step[stepName="CreateResourcesFromConfiguration"]/command',                                                                     'labmanager/createResourcesFromConfiguration.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="BulkCleanup"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                          'forms/BulkCleanup-Form.xml'],
    ['//step[stepName="BulkCleanup"]/command',                                                                                          'labmanager/bulkCleanup.pl'],
    ['//step[stepName="SetTimelimit"]/command',                                                                                         'setTimelimit.pl'],
    ['//procedure[procedureName="CloudManagerGrow"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                     'forms/Grow-Form.xml'],
    ['//step[stepName="grow"]/command',                                                                                                 'labmanager/step.grow.pl'],
    ['//procedure[procedureName="CloudManagerShrink"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                   'forms/Shrink-Form.xml'],
    ['//step[stepName="shrink"]/command',                                                                                               'labmanager/step.shrink.pl'],
    ['//procedure[procedureName="CloudManagerSync"]/propertySheet/property[propertyName="ec_parameterForm"]/value',                     'forms/Sync-Form.xml'],
    ['//procedure[procedureName="CloudManagerSync"]/step[stepName="sync"]/command',                                                     'labmanager/step.sync.pl'],

    ['//property[propertyName="ec_setup"]/value', 'ec_setup.pl'],
         );

